### ISSUE TITLE
Keccak256 and secp256k1 Support

### ISSUE THREAD

**Issue by databeforedishonor** [jeroen/openssl#117]
Is it possible to add support for keccak256 and secp256k1? I haven't found good viable options for these 2 within R.

Thanks

**Comment by jeroen** [comment]
I think the keccak version in openssl is sha3. If your bindings are built against libcrypto 3.0 or higher this should work:

```r
openssl:::rawstringhash('foo', 'sha3-256', NULL)
```

There is currently no R wrapper, but you can easily add one similar to sha2:

https://github.com/jeroen/openssl/blob/9eb04f6231bc98de31f17b344979f757128ec5d1/R/hash.R#L82-L86

**Comment by rmsams** [comment]
```r
openssl:::rawstringhash('foo', 'sha3-256', NULL)
[1] "76d3bc41c9f588f7fcd0d5bf4718f8f84b1c41b20882703100b9eb9413807c01"
```
but keccak256 is:

```
echo -n "foo" | keccak256   # using https://lib.rs/crates/keccak256-cli
0x41b1a0649752af1b28b3dc29a1556eee781e4a4c3a1f7f53f90fa834de098c4d
```

I believe keccak support was included in openssl here https://github.com/openssl/openssl/pull/16594

**Comment by rmsams** [comment]
@jeroen is there a fix to make `openssl:::rawstringhash('foo', 'keccak-256', NULL)` work? Keccak is widely used and implemented in openssl. 

Some background: 

keccak-256 _is_ sha3-256 in the sense that the keccak team won the [NIST hash function competition](https://en.wikipedia.org/wiki/NIST_hash_function_competition) in 2012 and published [FIPS 202](https://www.federalregister.gov/documents/2014/05/28/2014-12336/announcing-draft-federal-information-processing-standard-fips-202-sha-3-standard-permutation-based), which became the official [SHA-3 standard](https://www.nist.gov/news-events/news/2015/08/nist-releases-sha-3-cryptographic-hash-standard) in 2015. FIPS 202 contained some tweaks not in the team's original [implementation](https://keccak.team/software.html), so we're left with keccak-256 and (standard) sha3-256, and both are widely used.

**Comment by MrFlick** [comment]
@rmsams Apparently the [secretbase](https://github.com/shikokuchuo/secretbase/issues/9) package supports the algorithm if you need a solution now.

**Comment by rmsams** [comment]
> @rmsams Apparently the [secretbase](https://github.com/shikokuchuo/secretbase/issues/9) package supports the algorithm if you need a solution now.

I wasn't aware, thank's for the reference @MrFlick

**Comment by jeroen** [comment]
Thanks, I've tried to add it here to based on https://github.com/jeroen/openssl/issues/117#issuecomment-2072978413

**Comment by jeroen** [comment]
OK I have released this on CRAN. So you can use `keccak()` on Windows and Mac at least, but on Linux it requires a distro with at least libssl-dev 3.2 or newer.

**Comment by rmsams** [comment]
That was fast, thanks @jeroen !

>  but on Linux it requires a distro with at least libssl-dev 3.2 or newer.

Yes, that's a shame b/c it will take some time before libssl-dev >=3.2 makes it into the LTS releases of most linux distros. I suppose you could not export `keccak()` so that all the exposed user interfaces can be expected to work in a platform-independent way; those of us on linux who want the functionality will still have it, and be aware of the library dependency.

**Comment by jeroen** [comment]
This is why I am generally a bit reluctant to add this. Also this algorithm is not available on systems with alternative openssl implementations such as libressl. So you can use it locally on Windows and Mac, but if you want to write portable software that may be used by other people, I would recommend to stick with some of the more standard algorithms.

**Comment by rmsams** [comment]
Sure, I get it. But keccak is a primitive in most blockchain protocols so as far as sha3 implementation are concerned, it's here to stay and will propagate into most openssl implementations over time. Until that day arrives, maybe you can just keep `keccak()` as a non-exported, undocumented function if you want portability to be assumed for all the package's userland functions.
