### ISSUE TITLE
vulnerability reported in the openssl.so library 3.0.13

### ISSUE THREAD

**Issue by zoltickb** [jeroen/openssl#127]
Is it possibility to build the openssl R package with a later version of the openssl library. Tenable is reporting a vulnerability with the 3.0.13 release.

OpenSSL 3.0.0 < 3.0.15 Vulnerability

I installed the R openssl 2.2.2 package under R 4.4.2 but the openssl library is still at  version 3.0.13.

/usr/lib/R/library/openssl/libs# Rlist.R  | grep openssl
           openssl      2.2.2

/usr/lib/R/library/openssl/libs# strings openssl.so  | grep 3.3
OpenSSL 3.0.13 30 Jan 2024

Brad Zoltick
Email: zoltickb@mail.nih.gov

**Comment by jeroen** [comment]
Which operating system are you using?
