### ISSUE TITLE
 OpenSSL 1.1.1b breaks tests

### ISSUE THREAD

**Issue by daissi** [jeroen/openssl#63]
Hi,
OpenSSL 1.1.1b reached Debian and it causes the following error:

> test_check("openssl")
double free or corruption (fasttop)
Aborted

See [#923447](https://bugs.debian.org/923447)

**Comment by jeroen** [comment]
Thank you I'll have a look.

**Comment by jeroen** [comment]
It crashes here: https://github.com/jeroen/openssl/blob/master/src/base64.c#L32 Maybe that's a double free?

**Comment by jeroen** [comment]
I'll try to do a hotfix release today.

**Comment by jeroen** [comment]
I've published a hotfix release openssl 1.2.2 to CRAN that should fix the issue.

**Comment by daissi** [comment]
Thanks, very fast like usual ;-)

I will upload it to Debian later today.

**Comment by jeroen** [comment]
The real issue is a regression in libssl: https://github.com/openssl/openssl/issues/8375. Anyway the workaround is on CRAN now.

**Comment by daroczig** [comment]
Thanks :+1:
