### ISSUE TITLE
Add option to use semicolon for subject and issuer

### ISSUE THREAD

**Issue by hrbrmstr** [jeroen/openssl#72]
it's somewhat problematic to split `issuer` and `subject` as `<comma><space>` seems to be "a thing" now in the values for the individual fields. `XN_FLAG_SEP_SPLUS_SPC & ~ASN1_STRFLGS_ESC_MSB` would help compensate for that since semicolons are far less frequent as are `<semicolon><space>` instances.

Proposal (I can PR this) is to add a `SEXP semicolon` (or whatever you'd like the flag to be) toggle in `R_cert_info` that would note to use `XN_FLAG_SEP_SPLUS_SPC & ~ASN1_STRFLGS_ESC_MSB` vs `XN_FLAG_RFC2253 & ~ASN1_STRFLGS_ESC_MSB`. Multiline wld be even better but I saw the comment abt it being problematic.

That would then require something like adding `semicolon = getOption("OPENSSL_SEP_SEMICOLON", default = FALSE)` to the unexported `cert_info()` function since it's not exported and only called internally. 

Cld use an env var vs option. Cld also expose the function and formalize the param.

I've got ^^ ready in a PR but can change it to support whatever the desired approach is.

**Comment by jeroen** [comment]
Can we just make the default XN_FLAG_SEP_SPLUS_SPC? Or does that also have downsides? I'm not a fan of introducing global options if we can find a better default.

**Comment by hrbrmstr** [comment]
I'll run some tests on the "ugh" certs with that change this week (I can upload those as well). I def grok/sympathize with not wanting to use options. I more suggested it to avoid breaking anyone's existing code if they're doing something similar. 

(Re: the second comment) Aye. Def know that reference. And, it's unfortunate that causes issues b/c it's a handy quick fix to avoid pulling out those fields manually in C code (which is the super ugly option).

**Comment by jeroen** [comment]
OK there are simply too many flags to expose them one by one. Given that you are the only person that will use this, I exposed this in the [simplest possible way](https://github.com/jeroen/openssl/commit/5107a15edbfad24fbfe427c5d4f6f4081bc513b8) to just  pass the integer with the format flag.

So you'll probably want one of these values:

```
# define XN_FLAG_SEP_COMMA_PLUS  (1 << 16)/* RFC2253 ,+ */
# define XN_FLAG_SEP_CPLUS_SPC   (2 << 16)/* ,+ spaced: more readable */
# define XN_FLAG_SEP_SPLUS_SPC   (3 << 16)/* ;+ spaced */
# define XN_FLAG_SEP_MULTILINE   (4 << 16)/* One line per field */
```

**Comment by jeroen** [comment]
This is on CRAN now.
