### ISSUE TITLE
CentOS7 using R to install clusterProfiler get error about openssl

### ISSUE THREAD

**Issue by dailing57** [jeroen/openssl#87]
I've been having an unresolved error when I installed clusterProfiler using R on CentOS7. I have checked the information and some of them say it is the reason for installing the openssl version at the same time, but I have not found a specific solution.
`
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘openssl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib64/R/library/00LOCK-openssl/00new/openssl/libs/openssl.so':
  libssl.so.1.1: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib64/R/library/openssl’
ERROR: dependency ‘openssl’ is not available for package ‘httr’
* removing ‘/usr/lib64/R/library/httr’
ERROR: dependency ‘httr’ is not available for package ‘europepmc’
* removing ‘/usr/lib64/R/library/europepmc’
ERROR: dependency ‘europepmc’ is not available for package ‘enrichplot’
* removing ‘/usr/lib64/R/library/enrichplot’
ERROR: dependency ‘enrichplot’ is not available for package ‘clusterProfiler’
* removing ‘/usr/lib64/R/library/clusterProfiler’
`

**Comment by jeroen** [comment]
Can you show your full R package install log please. And also show your:

```sh
yum install openssl-devel
yum info openssl-devel
pkg-config --version openssl
```

**Comment by dailing57** [comment]
Thank you very much! After doing your instuction, the problem with openssl was solved, but a new problem is encountered:
`
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib64/R/library/xml2/libs/xml2.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
`
Could you please tell me what is the idea of solving this kind of problem?
Thank you from the bottom of my heart！
Here are the results of the new implementation of `BiocManager::install("clusterProfiler")`：
[R_info.txt](https://github.com/jeroen/openssl/files/6489333/R_info.txt)

**Comment by dailing57** [comment]
I've solved the problem. Thank you very much!
